<?php
namespace App\Services;

use App\Models\Router;

class MikrotikScriptService
{
    /**
     * Generate a complete MikroTik .rsc script for a router.
     */
    public function generate(Router $router): string
    {
        $radiusIp  = $this->resolveRadiusIp();
        $nasSecret = $router->radius_secret;
        $routerName = preg_replace('/[^a-zA-Z0-9\-]/', '-', $router->name);
        $billingDomain = $router->billing_domain ?: parse_url(config('app.url'), PHP_URL_HOST);
        $mgmtIps = env('MANAGEMENT_IPS', '192.168.88.1,10.0.0.1');
        $mgmtIpList = array_filter(array_map('trim', explode(',', $mgmtIps)));
        $customerIface = $router->customer_interface ?: 'bridge1';

        $lines = [];

        $lines[] = '# ============================================================';
        $lines[] = "# MikroTik Configuration Script for: {$router->name}";
        $lines[] = '# Generated by iNettotik ISP Billing System';
        $lines[] = '# Date: ' . now()->format('Y-m-d H:i:s');
        $lines[] = '# IMPORTANT: Review carefully before running!';
        $lines[] = '# ============================================================';
        $lines[] = '';

        // System Identity
        $lines[] = '# --- System Identity ---';
        $lines[] = "/system identity set name=\"{$routerName}\"";
        $lines[] = '';

        // Bridge / Customer Interface creation — auto-create if missing
        $lines[] = '# --- Customer Interface (Bridge) ---';
        $lines[] = "# Auto-create bridge '{$customerIface}' if it does not exist";
        $lines[] = ":if ([:len [/interface bridge find name=\"{$customerIface}\"]] = 0) do={";
        $lines[] = "  /interface bridge add name=\"{$customerIface}\" comment=\"Customer Bridge - iNettotik\" disabled=no";
        $lines[] = "}";
        $lines[] = "# NOTE: Add your customer-facing ethernet ports to the bridge manually:";
        $lines[] = "# /interface bridge port add bridge=\"{$customerIface}\" interface=ether2";
        $lines[] = "# /interface bridge port add bridge=\"{$customerIface}\" interface=ether3";
        $lines[] = "# /interface bridge port add bridge=\"{$customerIface}\" interface=ether4";
        $lines[] = "# /interface bridge port add bridge=\"{$customerIface}\" interface=ether5";
        $lines[] = '';

        // RADIUS client — nas-identifier is NOT supported in RouterOS v7; use /system identity instead
        $lines[] = '# --- RADIUS Client ---';
        $lines[] = '/radius remove [find]';
        $lines[] = '/radius add address=' . $radiusIp . ' secret="' . $nasSecret . '" service=ppp,hotspot,login';
        $lines[] = '/radius incoming set accept=yes port=3799';
        $lines[] = '';

        // PPPoE Pool
        $lines[] = '# --- IP Address Pools ---';
        $lines[] = "/ip pool remove [find name=\"pppoe-pool\"]";
        $lines[] = "/ip pool add name=\"pppoe-pool\" ranges={$router->pppoe_pool_range}";
        $lines[] = "/ip pool remove [find name=\"hotspot-pool\"]";
        $lines[] = "/ip pool add name=\"hotspot-pool\" ranges={$router->hotspot_pool_range}";
        $lines[] = '';

        // PPP Profiles — rate-limit must be omitted when empty; RADIUS supplies Mikrotik-Rate-Limit
        $lines[] = '# --- PPP Profiles ---';
        $lines[] = '/ppp profile remove [find name="pppoe-radius"]';
        $lines[] = '/ppp profile add name="pppoe-radius" local-address=pppoe-pool remote-address=pppoe-pool only-one=yes';
        $lines[] = '';

        // PPPoE Server
        $lines[] = '# --- PPPoE Server ---';
        $lines[] = "/interface pppoe-server server remove [find interface=\"{$customerIface}\"]";
        $lines[] = "/interface pppoe-server server add interface={$customerIface} service-name=\"pppoe-service\" default-profile=\"pppoe-radius\" authentication=mschap2,mschap1,chap,pap one-session-per-host=yes disabled=no";
        $lines[] = '';

        // Hotspot Setup — omit rate-limit and radius-default-domain
        $hotspotProfileCmd  = "/ip hotspot profile add name=\"hsprof-radius\"";
        $hotspotProfileCmd .= " hotspot-address=192.168.2.1 dns-name=\"{$billingDomain}\"";
        $hotspotProfileCmd .= " use-radius=yes radius-location-id=\"{$routerName}\"";
        $hotspotProfileCmd .= " login-by=http-pap,http-chap http-cookie-lifetime=1d";
        $lines[] = '# --- Hotspot Server ---';
        $lines[] = "/ip hotspot remove [find interface=\"{$customerIface}\"]";
        $lines[] = "/ip hotspot profile remove [find name=\"hsprof-radius\"]";
        $lines[] = $hotspotProfileCmd;
        $lines[] = "/ip hotspot add interface={$customerIface} address-pool=hotspot-pool profile=\"hsprof-radius\" name=\"hotspot-server\" disabled=no";
        $lines[] = '';

        // Hotspot Walled Garden
        $lines[] = '# --- Hotspot Walled Garden ---';
        $lines[] = '/ip hotspot walled-garden remove [find]';
        $lines[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"{$billingDomain}\" action=allow";
        $lines[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"*.{$billingDomain}\" action=allow";
        $lines[] = "/ip hotspot walled-garden ip add server=\"hotspot-server\" dst-address={$radiusIp} action=accept";
        $lines[] = '';

        // NAT Masquerade
        $lines[] = '# --- NAT Masquerade ---';
        $lines[] = "/ip firewall nat remove [find comment=\"ISP-NAT\"]";
        $lines[] = "/ip firewall nat add chain=srcnat out-interface={$router->wan_interface} action=masquerade comment=\"ISP-NAT\"";
        $lines[] = '';

        // Queue Types (PCQ)
        $lines[] = '# --- PCQ Queue Types ---';
        $lines[] = '/queue type remove [find name="pcq-download"]';
        $lines[] = '/queue type add name="pcq-download" kind=pcq pcq-rate=0 pcq-classifier=dst-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue type remove [find name="pcq-upload"]';
        $lines[] = '/queue type add name="pcq-upload" kind=pcq pcq-rate=0 pcq-classifier=src-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue tree remove [find name="Download"]';
        $lines[] = "/queue tree add name=\"Download\" parent={$router->wan_interface} queue=pcq-download";
        $lines[] = '/queue tree remove [find name="Upload"]';
        $lines[] = "/queue tree add name=\"Upload\" parent=global queue=pcq-upload";
        $lines[] = '';

        // Firewall Rules
        $lines[] = '# --- Firewall Rules ---';
        $lines[] = '# Drop invalid connections';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DROP-INVALID"]';
        $lines[] = '/ip firewall filter add chain=forward connection-state=invalid action=drop comment="ISP-DROP-INVALID"';
        $lines[] = '';
        $lines[] = '# Client-to-client blocking';
        $lines[] = '/ip firewall filter remove [find comment="ISP-NO-CLIENT2CLIENT"]';
        $lines[] = "/ip firewall filter add chain=forward in-interface={$customerIface} out-interface={$customerIface} action=drop comment=\"ISP-NO-CLIENT2CLIENT\"";
        $lines[] = '';
        $lines[] = '# Brute force SSH protection';
        $lines[] = '/ip firewall filter remove [find comment="ISP-BRUTE-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new src-address-list=ssh-bruteforce action=drop comment="ISP-BRUTE-SSH"';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DETECT-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new action=add-src-to-address-list address-list=ssh-bruteforce address-list-timeout=1h comment="ISP-DETECT-SSH"';
        $lines[] = '';

        // Management IP whitelist
        if (!empty($mgmtIpList)) {
            $lines[] = '# Management IP Whitelist';
            $lines[] = '/ip firewall address-list remove [find list="mgmt-allowed"]';
            foreach ($mgmtIpList as $ip) {
                $lines[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$ip} comment=\"Management\"";
            }
            // Also add the RADIUS/billing server IP to the allowed list
            $lines[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$radiusIp} comment=\"Billing Server\"";
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-ALLOW"]';
            $lines[] = '/ip firewall filter add chain=input src-address-list=mgmt-allowed action=accept place-before=0 comment="ISP-MGMT-ALLOW"';
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-DROP"]';
            $lines[] = '/ip firewall filter add chain=input action=drop src-address-list=!mgmt-allowed in-interface=' . $router->wan_interface . ' protocol=tcp dst-port=22,8291 comment="ISP-MGMT-DROP"';
            $lines[] = '';
        }

        // Disable unnecessary services
        $lines[] = '# --- Disable Unnecessary Services ---';
        $lines[] = '/ip service disable telnet,ftp,www-ssl,api-ssl';
        $lines[] = '/ip service enable ssh,winbox,api';
        $lines[] = '/ip service set ssh port=22';
        $lines[] = '/ip service set winbox port=8291';
        $lines[] = '/ip service set api port=8728';
        $lines[] = '';

        // NTP
        $lines[] = '# --- NTP Client ---';
        $lines[] = '# NOTE: RouterOS v6 uses: /system ntp client set enabled=yes primary-ntp=216.239.35.0 secondary-ntp=216.239.35.4';
        $lines[] = '# The commands below use RouterOS v7 syntax:';
        $lines[] = '/system ntp client set enabled=yes';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.0 } on-error={}';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.4 } on-error={}';
        $lines[] = '';

        // DNS
        $lines[] = '# --- DNS ---';
        $lines[] = '/ip dns set allow-remote-requests=yes servers=8.8.8.8,1.1.1.1';
        $lines[] = '';

        // Report WAN IP for reference
        $lines[] = '# --- Report WAN IP ---';
        $lines[] = ':local wanIP [/ip address get [find interface=' . $router->wan_interface . '] address]';
        $lines[] = ':put ("WAN IP: " . $wanIP)';
        $lines[] = '';

        $lines[] = '# ============================================================';
        $lines[] = '# Script completed. Reboot is NOT required.';
        $lines[] = "# Router Name: {$routerName}";
        $lines[] = "# RADIUS Server: {$radiusIp}";
        $lines[] = '# ============================================================';

        return implode("\n", $lines);
    }

    /**
     * Resolve the RADIUS server IP to use in generated scripts.
     * Prefers RADIUS_SERVER_IP env var, then app.url host, never returns empty.
     */
    protected function resolveRadiusIp(): string
    {
        $ip = config('radius.server_ip', env('RADIUS_SERVER_IP', ''));
        if ($ip) {
            return $ip;
        }
        $host = parse_url(config('app.url'), PHP_URL_HOST);
        return $host ?: '127.0.0.1';
    }
}
