<?php
namespace App\Services;

use App\Models\Router;

class MikrotikScriptService
{
    /**
     * Generate a complete MikroTik .rsc script for a router.
     */
    public function generate(Router $router): string
    {
        $billingServerIp = $this->resolveRadiusIp();
        $billingPort     = env('BILLING_PORT', '8090');
        $callbackUrl     = "http://{$billingServerIp}:{$billingPort}/api/router-callback";
        $routerName      = preg_replace('/[^a-zA-Z0-9\-]/', '-', $router->name);
        $billingDomain   = $router->billing_domain ?: parse_url(config('app.url'), PHP_URL_HOST);
        $mgmtIps         = env('MANAGEMENT_IPS', '192.168.88.1,10.0.0.1');
        $mgmtIpList      = array_filter(array_map('trim', explode(',', $mgmtIps)));
        $customerIface   = $router->customer_interface ?: 'bridge1';
        $wanIface        = $router->wan_interface ?: 'ether1';

        // WireGuard VPN octet: router 1 = .2, router 2 = .3, etc.
        $wgOctet    = (($router->id % 253) + 2);
        $wgRouterIp = "10.255.255.{$wgOctet}/32";
        $wgServerIp = '10.255.255.1/32';
        $wgPort     = 13231;

        $lines = [];

        // ── Header ────────────────────────────────────────────────────────────
        $lines[] = '# ============================================================';
        $lines[] = "# MikroTik Configuration Script for: {$router->name}";
        $lines[] = '# Generated by iNettotik ISP Billing System';
        $lines[] = '# Date: ' . now()->format('Y-m-d H:i:s');
        $lines[] = '# IMPORTANT: Review the variables below before running!';
        $lines[] = '# ============================================================';
        $lines[] = '';

        // ── Variables block ───────────────────────────────────────────────────
        $lines[] = '# --- Configuration Variables (EDIT THESE) ---';
        $lines[] = ":local routerName \"{$routerName}\"";
        $lines[] = ":local billingServerIP \"{$billingServerIp}\"";
        $lines[] = ":local wgRouterIP \"{$wgRouterIp}\"";
        $lines[] = ":local wgServerIP \"{$wgServerIp}\"";
        $lines[] = ":local wgPort {$wgPort}";
        $lines[] = ':local billingPublicKey "REPLACE_WITH_BILLING_SERVER_PUBLIC_KEY"';
        $lines[] = ":local callbackURL \"{$callbackUrl}\"";
        $lines[] = ":local radiusSecret \"{$router->radius_secret}\"";
        $lines[] = ":local wanInterface \"{$wanIface}\"";
        $lines[] = ":local customerInterface \"{$customerIface}\"";
        $lines[] = ":local pppoePoolRange \"{$router->pppoe_pool_range}\"";
        $lines[] = ":local hotspotPoolRange \"{$router->hotspot_pool_range}\"";
        $lines[] = ":local billingDomain \"{$billingDomain}\"";
        $lines[] = ':local wgSubnet "10.255.255.0/24"';
        $lines[] = '';

        // ── System Identity ───────────────────────────────────────────────────
        $lines[] = '# --- System Identity ---';
        $lines[] = '/system identity set name=$routerName';
        $lines[] = '';

        // ── Bridge / Customer Interface ───────────────────────────────────────
        $lines[] = '# --- Customer Interface (Bridge) ---';
        $lines[] = '# Auto-create the customer bridge if it does not exist';
        $lines[] = ':if ([:len [/interface bridge find name=$customerInterface]] = 0) do={';
        $lines[] = '  /interface bridge add name=$customerInterface comment="Customer Bridge - iNettotik" disabled=no';
        $lines[] = '}';
        $lines[] = '# NOTE: Add your customer-facing ethernet ports to the bridge manually:';
        $lines[] = '# /interface bridge port add bridge=$customerInterface interface=ether2';
        $lines[] = '# /interface bridge port add bridge=$customerInterface interface=ether3';
        $lines[] = '# /interface bridge port add bridge=$customerInterface interface=ether4';
        $lines[] = '# /interface bridge port add bridge=$customerInterface interface=ether5';
        $lines[] = '';

        // ── RADIUS Client ─────────────────────────────────────────────────────
        $lines[] = '# --- RADIUS Client ---';
        $lines[] = '/radius remove [find]';
        $lines[] = '/radius add address=$billingServerIP secret=$radiusSecret service=ppp,hotspot,login';
        $lines[] = '/radius incoming set accept=yes port=3799';
        $lines[] = '';

        // ── IP Address Pools ──────────────────────────────────────────────────
        $lines[] = '# --- IP Address Pools ---';
        $lines[] = '/ip pool remove [find name="pppoe-pool"]';
        $lines[] = '/ip pool add name="pppoe-pool" ranges=$pppoePoolRange';
        $lines[] = '/ip pool remove [find name="hotspot-pool"]';
        $lines[] = '/ip pool add name="hotspot-pool" ranges=$hotspotPoolRange';
        $lines[] = '';

        // ── PPP Profiles ──────────────────────────────────────────────────────
        $lines[] = '# --- PPP Profiles ---';
        $lines[] = '/ppp profile remove [find name="pppoe-radius"]';
        $lines[] = '/ppp profile add name="pppoe-radius" local-address=pppoe-pool remote-address=pppoe-pool only-one=yes';
        $lines[] = '';

        // ── PPPoE Server ──────────────────────────────────────────────────────
        $lines[] = '# --- PPPoE Server ---';
        $lines[] = '/interface pppoe-server server remove [find interface=$customerInterface]';
        $lines[] = '/interface pppoe-server server add interface=$customerInterface service-name="pppoe-service" default-profile="pppoe-radius" authentication=mschap2,mschap1,chap,pap one-session-per-host=yes disabled=no';
        $lines[] = '';

        // ── Hotspot Server ────────────────────────────────────────────────────
        $lines[] = '# --- Hotspot Server ---';
        $lines[] = '/ip hotspot remove [find interface=$customerInterface]';
        $lines[] = '/ip hotspot profile remove [find name="hsprof-radius"]';
        $lines[] = '/ip hotspot profile add name="hsprof-radius" hotspot-address=192.168.2.1 dns-name=$billingDomain use-radius=yes radius-location-id=$routerName login-by=http-pap,http-chap http-cookie-lifetime=1d';
        $lines[] = '/ip hotspot add interface=$customerInterface address-pool=hotspot-pool profile="hsprof-radius" name="hotspot-server" disabled=no';
        $lines[] = '';

        // ── Hotspot Walled Garden ─────────────────────────────────────────────
        $lines[] = '# --- Hotspot Walled Garden ---';
        $lines[] = '/ip hotspot walled-garden remove [find]';
        $lines[] = '/ip hotspot walled-garden add server="hotspot-server" dst-host=$billingDomain action=allow';
        $lines[] = '/ip hotspot walled-garden add server="hotspot-server" dst-host=("*." . $billingDomain) action=allow';
        $lines[] = '/ip hotspot walled-garden ip add server="hotspot-server" dst-address=$billingServerIP action=accept';
        $lines[] = '';

        // ── NAT Masquerade ────────────────────────────────────────────────────
        $lines[] = '# --- NAT Masquerade ---';
        $lines[] = '/ip firewall nat remove [find comment="ISP-NAT"]';
        $lines[] = '/ip firewall nat add chain=srcnat out-interface=$wanInterface action=masquerade comment="ISP-NAT"';
        $lines[] = '';

        // ── PCQ Queue Types ───────────────────────────────────────────────────
        $lines[] = '# --- PCQ Queue Types ---';
        $lines[] = '/queue type remove [find name="pcq-download"]';
        $lines[] = '/queue type add name="pcq-download" kind=pcq pcq-rate=0 pcq-classifier=dst-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue type remove [find name="pcq-upload"]';
        $lines[] = '/queue type add name="pcq-upload" kind=pcq pcq-rate=0 pcq-classifier=src-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue tree remove [find name="Download"]';
        $lines[] = '/queue tree add name="Download" parent=$wanInterface queue=pcq-download';
        $lines[] = '/queue tree remove [find name="Upload"]';
        $lines[] = '/queue tree add name="Upload" parent=global queue=pcq-upload';
        $lines[] = '';

        // ── Firewall Rules ────────────────────────────────────────────────────
        $lines[] = '# --- Firewall Rules ---';
        $lines[] = '# Drop invalid connections';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DROP-INVALID"]';
        $lines[] = '/ip firewall filter add chain=forward connection-state=invalid action=drop comment="ISP-DROP-INVALID"';
        $lines[] = '';
        $lines[] = '# Client-to-client blocking';
        $lines[] = '/ip firewall filter remove [find comment="ISP-NO-CLIENT2CLIENT"]';
        $lines[] = '/ip firewall filter add chain=forward in-interface=$customerInterface out-interface=$customerInterface action=drop comment="ISP-NO-CLIENT2CLIENT"';
        $lines[] = '';
        $lines[] = '# Brute force SSH protection';
        $lines[] = '/ip firewall filter remove [find comment="ISP-BRUTE-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new src-address-list=ssh-bruteforce action=drop comment="ISP-BRUTE-SSH"';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DETECT-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new action=add-src-to-address-list address-list=ssh-bruteforce address-list-timeout=1h comment="ISP-DETECT-SSH"';
        $lines[] = '';

        // ── Management IP Whitelist ───────────────────────────────────────────
        if (!empty($mgmtIpList)) {
            $lines[] = '# Management IP Whitelist';
            $lines[] = '/ip firewall address-list remove [find list="mgmt-allowed"]';
            foreach ($mgmtIpList as $ip) {
                $lines[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$ip} comment=\"Management\"";
            }
            // Always allow the billing/RADIUS server for management access
            $lines[] = '/ip firewall address-list add list="mgmt-allowed" address=$billingServerIP comment="Billing Server"';
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-ALLOW"]';
            $lines[] = '/ip firewall filter add chain=input src-address-list=mgmt-allowed action=accept place-before=0 comment="ISP-MGMT-ALLOW"';
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-DROP"]';
            $lines[] = '/ip firewall filter add chain=input action=drop src-address-list=!mgmt-allowed in-interface=$wanInterface protocol=tcp dst-port=22,8291 comment="ISP-MGMT-DROP"';
            $lines[] = '';
        }

        // ── Disable Unnecessary Services ──────────────────────────────────────
        $lines[] = '# --- Disable Unnecessary Services ---';
        $lines[] = '/ip service disable telnet,ftp,www-ssl,api-ssl';
        $lines[] = '/ip service enable ssh,winbox,api';
        $lines[] = '/ip service set ssh port=22';
        $lines[] = '/ip service set winbox port=8291';
        $lines[] = '/ip service set api port=8728';
        $lines[] = '';

        // ── NTP Client ────────────────────────────────────────────────────────
        $lines[] = '# --- NTP Client ---';
        $lines[] = ':do { /system ntp client set enabled=yes } on-error={}';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.0 } on-error={}';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.4 } on-error={}';
        $lines[] = '';

        // ── DNS ───────────────────────────────────────────────────────────────
        $lines[] = '# --- DNS ---';
        $lines[] = '/ip dns set allow-remote-requests=yes servers=8.8.8.8,1.1.1.1';
        $lines[] = '';

        // ── WireGuard Management Tunnel ───────────────────────────────────────
        $lines[] = '# --- WireGuard Management Tunnel (wg-billing) ---';
        $lines[] = '/interface wireguard remove [find name="wg-billing"]';
        $lines[] = '/interface wireguard add name="wg-billing" listen-port=$wgPort mtu=1420 comment="iNettotik Billing Tunnel"';
        $lines[] = ':local wgPrivKey [/interface wireguard get [find name="wg-billing"] private-key]';
        $lines[] = ':local wgPubKey [/interface wireguard get [find name="wg-billing"] public-key]';
        $lines[] = '';
        $lines[] = '# Assign VPN IP to the WireGuard interface';
        $lines[] = '/ip address remove [find interface="wg-billing"]';
        $lines[] = '/ip address add address=$wgRouterIP interface="wg-billing" comment="iNettotik VPN IP"';
        $lines[] = '';
        $lines[] = '# Add billing server as WireGuard peer';
        $lines[] = '/interface wireguard peers remove [find interface="wg-billing"]';
        $lines[] = '/interface wireguard peers add interface="wg-billing" \\';
        $lines[] = '    public-key=$billingPublicKey \\';
        $lines[] = '    endpoint-address=$billingServerIP \\';
        $lines[] = '    endpoint-port=$wgPort \\';
        $lines[] = '    allowed-address=($wgServerIP . "," . $wgSubnet) \\';
        $lines[] = '    persistent-keepalive=25s \\';
        $lines[] = '    comment="iNettotik Billing Server"';
        $lines[] = '';
        $lines[] = '# Allow WireGuard through firewall';
        $lines[] = '/ip firewall filter remove [find comment="ISP-WG-BILLING"]';
        $lines[] = '/ip firewall filter add chain=input protocol=udp dst-port=$wgPort action=accept comment="ISP-WG-BILLING" place-before=0';
        $lines[] = '';

        // ── Auto-Register with Billing Server ─────────────────────────────────
        $lines[] = '# --- Auto-Register with Billing Server ---';
        $lines[] = '# Detect WAN IP automatically';
        $lines[] = ':local wanIP ""';
        $lines[] = ':do {';
        $lines[] = '    :set wanIP [/ip address get [find interface=$wanInterface] address]';
        $lines[] = '    # Strip the /mask suffix';
        $lines[] = '    :set wanIP [:pick $wanIP 0 [:find $wanIP "/"]]';
        $lines[] = '} on-error={';
        $lines[] = '    :put "WARNING: Could not detect WAN IP on $wanInterface"';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '# Get VPN IP (strip mask)';
        $lines[] = ':local vpnIP ""';
        $lines[] = ':do {';
        $lines[] = '    :set vpnIP [/ip address get [find interface="wg-billing"] address]';
        $lines[] = '    :set vpnIP [:pick $vpnIP 0 [:find $vpnIP "/"]]';
        $lines[] = '} on-error={';
        $lines[] = '    :put "WARNING: Could not detect VPN IP"';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '# Get WireGuard public key for this router';
        $lines[] = ':local routerPubKey ""';
        $lines[] = ':do {';
        $lines[] = '    :set routerPubKey [/interface wireguard get [find name="wg-billing"] public-key]';
        $lines[] = '} on-error={}';
        $lines[] = '';
        $lines[] = '# POST to billing server';
        $lines[] = ':do {';
        $lines[] = '    /tool fetch url=$callbackURL \\';
        $lines[] = '        http-method=post \\';
        $lines[] = '        http-header-field="Content-Type: application/json" \\';
        $lines[] = '        http-data=("{\"router_name\":\"" . $routerName . "\",\"wan_ip\":\"" . $wanIP . "\",\"vpn_ip\":\"" . $vpnIP . "\",\"radius_secret\":\"" . $radiusSecret . "\",\"wg_public_key\":\"" . $routerPubKey . "\"}") \\';
        $lines[] = '        output=none';
        $lines[] = '    :put ""';
        $lines[] = '    :put "=============================================="';
        $lines[] = '    :put "  Router registered in iNettotik database!"';
        $lines[] = '    :put "  Check the billing panel."';
        $lines[] = '    :put "=============================================="';
        $lines[] = '    :put "  Router:     $routerName"';
        $lines[] = '    :put "  WAN IP:     $wanIP"';
        $lines[] = '    :put "  VPN IP:     $vpnIP"';
        $lines[] = '    :put "  WG PubKey:  $routerPubKey"';
        $lines[] = '    :put "=============================================="';
        $lines[] = '} on-error={';
        $lines[] = '    :put ""';
        $lines[] = '    :put "WARNING: Could not reach billing server at $callbackURL"';
        $lines[] = '    :put "Router details for manual entry:"';
        $lines[] = '    :put "  Router:     $routerName"';
        $lines[] = '    :put "  WAN IP:     $wanIP"';
        $lines[] = '    :put "  VPN IP:     $vpnIP"';
        $lines[] = '    :put "  WG PubKey:  $routerPubKey"';
        $lines[] = '    :put "  Secret:     $radiusSecret"';
        $lines[] = '}';

        return implode("\n", $lines);
    }

    /**
     * Resolve the billing/RADIUS server IP to use in generated scripts.
     * Prefers RADIUS_SERVER_IP env var, then app.url host, never returns empty.
     */
    protected function resolveRadiusIp(): string
    {
        $ip = config('radius.server_ip', env('RADIUS_SERVER_IP', ''));
        if ($ip) {
            return $ip;
        }
        $host = parse_url(config('app.url'), PHP_URL_HOST);
        return $host ?: '127.0.0.1';
    }
}
