<?php
namespace App\Services;

use App\Models\Router;

class MikrotikScriptService
{
    /**
     * Generate a complete MikroTik .rsc script for a router.
     *
     * All configuration values are inlined as literals — no RouterOS :local
     * variables are used for config data, so the script is safe to paste
     * line-by-line into the MikroTik terminal without scope issues.
     */
    public function generate(Router $router): string
    {
        $radiusIp      = $this->resolveRadiusIp();
        $nasSecret     = $router->radius_secret;
        $routerName    = preg_replace('/[^a-zA-Z0-9\-]/', '-', $router->name);
        $billingDomain = $router->billing_domain ?: parse_url(config('app.url'), PHP_URL_HOST);
        $mgmtIps       = env('MANAGEMENT_IPS', '192.168.88.1,10.0.0.1');
        $mgmtIpList    = array_filter(array_map('trim', explode(',', $mgmtIps)));
        $customerIface = $router->customer_interface ?: 'bridge1';
        $wanIface      = $router->wan_interface ?: 'ether1';

        // WireGuard config — unique per-router VPN IP derived from router ID
        $wgPort      = 13231;
        $octet       = (($router->id - 1) % 253) + 2;
        $wgRouterIP  = "10.255.255.{$octet}";
        $wgSubnet    = '10.255.255.0/24';
        $billingPort = env('BILLING_PORT', '8090');
        $callbackUrl = "http://{$radiusIp}:{$billingPort}/api/router-callback";

        $pppoeRange   = $router->pppoe_pool_range;
        $hotspotRange = $router->hotspot_pool_range;

        $lines = [];

        // Header
        $lines[] = '# ============================================================';
        $lines[] = "# MikroTik Configuration Script for: {$router->name}";
        $lines[] = '# Generated by iNettotik ISP Billing System';
        $lines[] = '# Date: ' . now()->format('Y-m-d H:i:s');
        $lines[] = '# IMPORTANT: Review carefully before running!';
        $lines[] = '# ============================================================';
        $lines[] = '# Configuration Reference (DO NOT EDIT - for reference only):';
        $lines[] = "#   Router Name:      {$routerName}";
        $lines[] = "#   Billing Server:   {$radiusIp}";
        $lines[] = "#   RADIUS Secret:    {$nasSecret}";
        $lines[] = "#   WAN Interface:    {$wanIface}";
        $lines[] = "#   Customer Bridge:  {$customerIface}";
        $lines[] = "#   PPPoE Pool:       {$pppoeRange}";
        $lines[] = "#   Hotspot Pool:     {$hotspotRange}";
        $lines[] = "#   Billing Domain:   {$billingDomain}";
        $lines[] = "#   WG Router IP:     {$wgRouterIP}/32";
        $lines[] = "#   WG Port:          {$wgPort}";
        $lines[] = '# ============================================================';
        $lines[] = '';

        // System Identity
        $lines[] = '# --- System Identity ---';
        $lines[] = "/system identity set name=\"{$routerName}\"";
        $lines[] = '';

        // Bridge / Customer Interface creation
        $lines[] = '# --- Customer Interface (Bridge) ---';
        $lines[] = ":if ([:len [/interface bridge find name=\"{$customerIface}\"]] = 0) do={";
        $lines[] = "  /interface bridge add name=\"{$customerIface}\" comment=\"Customer Bridge - iNettotik\" disabled=no";
        $lines[] = '}';
        $lines[] = '';

        // RADIUS client
        $lines[] = '# --- RADIUS Client ---';
        $lines[] = '/radius remove [find]';
        $lines[] = "/radius add address={$radiusIp} secret=\"{$nasSecret}\" service=ppp,hotspot,login";
        $lines[] = '/radius incoming set accept=yes port=3799';
        $lines[] = '';

        // IP Address Pools — literal range values, no variables
        $lines[] = '# --- IP Address Pools ---';
        $lines[] = '/ip pool remove [find name="pppoe-pool"]';
        $lines[] = "/ip pool add name=\"pppoe-pool\" ranges={$pppoeRange}";
        $lines[] = '/ip pool remove [find name="hotspot-pool"]';
        $lines[] = "/ip pool add name=\"hotspot-pool\" ranges={$hotspotRange}";
        $lines[] = '';

        // PPP Profiles
        $lines[] = '# --- PPP Profiles ---';
        $lines[] = '/ppp profile remove [find name="pppoe-radius"]';
        $lines[] = '/ppp profile add name="pppoe-radius" use-radius=yes local-address=pppoe-pool remote-address=pppoe-pool only-one=yes';
        $lines[] = '';

        // PPPoE Server — literal interface name
        $lines[] = '# --- PPPoE Server ---';
        $lines[] = "/interface pppoe-server server remove [find interface=\"{$customerIface}\"]";
        $lines[] = "/interface pppoe-server server add interface={$customerIface} service-name=\"pppoe-service\" default-profile=\"pppoe-radius\" authentication=mschap2,mschap1,chap,pap one-session-per-host=yes disabled=no";
        $lines[] = '';

        // Hotspot — no radius-default-domain, literal values throughout
        $lines[] = '# --- Hotspot Server ---';
        $lines[] = "/ip hotspot remove [find interface=\"{$customerIface}\"]";
        $lines[] = '/ip hotspot profile remove [find name="hsprof-radius"]';
        $lines[] = "/ip hotspot profile add name=\"hsprof-radius\" hotspot-address=192.168.2.1 dns-name=\"{$billingDomain}\" use-radius=yes radius-location-id=\"{$routerName}\" login-by=http-pap,http-chap http-cookie-lifetime=1d";
        $lines[] = "/ip hotspot add interface={$customerIface} address-pool=hotspot-pool profile=\"hsprof-radius\" name=\"hotspot-server\" disabled=no";
        $lines[] = '';

        // Hotspot Walled Garden — literal IP and domain
        $lines[] = '# --- Hotspot Walled Garden ---';
        $lines[] = '/ip hotspot walled-garden remove [find]';
        $lines[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"{$billingDomain}\" action=allow";
        $lines[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"*.{$billingDomain}\" action=allow";
        $lines[] = "/ip hotspot walled-garden ip add server=\"hotspot-server\" dst-address={$radiusIp} action=accept";
        $lines[] = '';

        // NAT Masquerade — literal WAN interface name
        $lines[] = '# --- NAT Masquerade ---';
        $lines[] = '/ip firewall nat remove [find comment="ISP-NAT"]';
        $lines[] = "/ip firewall nat add chain=srcnat out-interface={$wanIface} action=masquerade comment=\"ISP-NAT\"";
        $lines[] = '';

        // Queue Types (PCQ) — literal interface names
        $lines[] = '# --- PCQ Queue Types ---';
        $lines[] = '/queue type remove [find name="pcq-download"]';
        $lines[] = '/queue type add name="pcq-download" kind=pcq pcq-rate=0 pcq-classifier=dst-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue type remove [find name="pcq-upload"]';
        $lines[] = '/queue type add name="pcq-upload" kind=pcq pcq-rate=0 pcq-classifier=src-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $lines[] = '/queue tree remove [find name="Download"]';
        $lines[] = "/queue tree add name=\"Download\" parent={$wanIface} queue=pcq-download";
        $lines[] = '/queue tree remove [find name="Upload"]';
        $lines[] = '/queue tree add name="Upload" parent=global queue=pcq-upload';
        $lines[] = '';

        // Firewall Rules — literal interface names, literal port numbers
        $lines[] = '# --- Firewall Rules ---';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DROP-INVALID"]';
        $lines[] = '/ip firewall filter add chain=forward connection-state=invalid action=drop comment="ISP-DROP-INVALID"';
        $lines[] = '';
        $lines[] = '/ip firewall filter remove [find comment="ISP-NO-CLIENT2CLIENT"]';
        $lines[] = "/ip firewall filter add chain=forward in-interface={$customerIface} out-interface={$customerIface} action=drop comment=\"ISP-NO-CLIENT2CLIENT\"";
        $lines[] = '';
        $lines[] = '/ip firewall filter remove [find comment="ISP-BRUTE-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new src-address-list=ssh-bruteforce action=drop comment="ISP-BRUTE-SSH"';
        $lines[] = '/ip firewall filter remove [find comment="ISP-DETECT-SSH"]';
        $lines[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new action=add-src-to-address-list address-list=ssh-bruteforce address-list-timeout=1h comment="ISP-DETECT-SSH"';
        $lines[] = '';

        // Management IP whitelist — literal addresses
        if (!empty($mgmtIpList)) {
            $lines[] = '# Management IP Whitelist';
            $lines[] = '/ip firewall address-list remove [find list="mgmt-allowed"]';
            foreach ($mgmtIpList as $ip) {
                $lines[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$ip} comment=\"Management\"";
            }
            $lines[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$radiusIp} comment=\"Billing Server\"";
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-ALLOW"]';
            $lines[] = '/ip firewall filter add chain=input src-address-list=mgmt-allowed action=accept place-before=0 comment="ISP-MGMT-ALLOW"';
            $lines[] = '/ip firewall filter remove [find comment="ISP-MGMT-DROP"]';
            $lines[] = "/ip firewall filter add chain=input action=drop src-address-list=!mgmt-allowed in-interface={$wanIface} protocol=tcp dst-port=22,8291 comment=\"ISP-MGMT-DROP\"";
            $lines[] = '';
        }

        // Disable unnecessary services
        $lines[] = '# --- Disable Unnecessary Services ---';
        $lines[] = '/ip service disable telnet,ftp,www-ssl,api-ssl';
        $lines[] = '/ip service enable ssh,winbox,api';
        $lines[] = '/ip service set ssh port=22';
        $lines[] = '/ip service set winbox port=8291';
        $lines[] = '/ip service set api port=8728';
        $lines[] = '';

        // NTP — use :do{} to handle duplicate-address errors on re-runs
        $lines[] = '# --- NTP Client ---';
        $lines[] = ':do { /system ntp client set enabled=yes } on-error={}';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.0 } on-error={}';
        $lines[] = ':do { /system ntp client servers add address=216.239.35.4 } on-error={}';
        $lines[] = '';

        // DNS
        $lines[] = '# --- DNS ---';
        $lines[] = '/ip dns set allow-remote-requests=yes servers=8.8.8.8,1.1.1.1';
        $lines[] = '';

        // WireGuard Management Tunnel — literal port and IP values
        $lines[] = '# --- WireGuard Management Tunnel ---';
        $lines[] = '/interface wireguard remove [find name="wg-billing"]';
        $lines[] = "/interface wireguard add name=\"wg-billing\" listen-port={$wgPort} mtu=1420 comment=\"iNettotik Billing Tunnel\"";
        $lines[] = '';
        $lines[] = '# Assign VPN IP';
        $lines[] = '/ip address remove [find interface="wg-billing"]';
        $lines[] = "/ip address add address={$wgRouterIP}/32 interface=\"wg-billing\" comment=\"iNettotik VPN IP\"";
        $lines[] = '';
        $lines[] = '# Add billing server peer';
        $lines[] = '# NOTE: Replace REPLACE_WITH_BILLING_SERVER_PUBLIC_KEY with your actual WireGuard server public key';
        $lines[] = '/interface wireguard peers remove [find interface="wg-billing"]';
        $lines[] = "/interface wireguard peers add interface=\"wg-billing\" public-key=\"REPLACE_WITH_BILLING_SERVER_PUBLIC_KEY\" endpoint-address={$radiusIp} endpoint-port={$wgPort} allowed-address={$wgSubnet} persistent-keepalive=25s comment=\"iNettotik Billing Server\"";
        $lines[] = '';
        $lines[] = '# Allow WireGuard through firewall';
        $lines[] = '/ip firewall filter remove [find comment="ISP-WG-BILLING"]';
        $lines[] = "/ip firewall filter add chain=input protocol=udp dst-port={$wgPort} action=accept comment=\"ISP-WG-BILLING\"";
        $lines[] = '';

        // Auto-register callback — wrapped in { } so :local vars maintain scope within the block
        $lines[] = '# --- Auto-Register with Billing Server ---';
        $lines[] = '# This section runs as a single script block to detect IPs and POST back to billing server';
        $lines[] = '{';
        $lines[] = ':local wanIP ""';
        $lines[] = ':local vpnIP ""';
        $lines[] = ':local routerPubKey ""';
        $lines[] = ':do {';
        $lines[] = "  :set wanIP [/ip address get [find interface={$wanIface}] address]";
        $lines[] = '  :set wanIP [:pick $wanIP 0 [:find $wanIP "/"]]';
        $lines[] = '} on-error={ :put "WARNING: Could not detect WAN IP" }';
        $lines[] = ':do {';
        $lines[] = '  :set vpnIP [/ip address get [find interface="wg-billing"] address]';
        $lines[] = '  :set vpnIP [:pick $vpnIP 0 [:find $vpnIP "/"]]';
        $lines[] = '} on-error={ :put "WARNING: Could not detect VPN IP" }';
        $lines[] = ':do {';
        $lines[] = '  :set routerPubKey [/interface wireguard get [find name="wg-billing"] public-key]';
        $lines[] = '} on-error={}';
        $lines[] = ':do {';
        $lines[] = "  /tool fetch url=\"{$callbackUrl}\" http-method=post http-header-field=\"Content-Type: application/json\" http-data=(\"{\\\"router_name\\\":\\\"{$routerName}\\\",\\\"wan_ip\\\":\\\"\" . \$wanIP . \"\\\",\\\"vpn_ip\\\":\\\"\" . \$vpnIP . \"\\\",\\\"radius_secret\\\":\\\"{$nasSecret}\\\",\\\"wg_public_key\\\":\\\"\" . \$routerPubKey . \"\\\"}\" ) output=none";
        $lines[] = '  :put "SUCCESS: Router registered with billing server!"';
        $lines[] = '  :put ("WAN IP: " . $wanIP)';
        $lines[] = '  :put ("VPN IP: " . $vpnIP)';
        $lines[] = '  :put ("WG Key: " . $routerPubKey)';
        $lines[] = '} on-error={';
        $lines[] = '  :put "WARNING: Could not reach billing server"';
        $lines[] = '  :put ("WAN IP: " . $wanIP)';
        $lines[] = '  :put ("VPN IP: " . $vpnIP)';
        $lines[] = '  :put ("WG Key: " . $routerPubKey)';
        $lines[] = "  :put \"Secret: {$nasSecret}\"";
        $lines[] = '}';
        $lines[] = '}';

        return implode("\n", $lines);
    }

    /**
     * Resolve the RADIUS server IP to use in generated scripts.
     * Prefers RADIUS_SERVER_IP env var, then app.url host, never returns empty.
     */
    protected function resolveRadiusIp(): string
    {
        $ip = config('radius.server_ip', env('RADIUS_SERVER_IP', ''));
        if ($ip) {
            return $ip;
        }
        $host = parse_url(config('app.url'), PHP_URL_HOST);
        return $host ?: '127.0.0.1';
    }
}
