<?php
return [
    'gateways' => [
        'mpesa_paybill' => [
            'enabled'          => env('MPESA_PAYBILL_ENABLED', true),
            'label'            => 'M-Pesa Paybill',
            'environment'      => env('MPESA_ENV', 'sandbox'),
            'consumer_key'     => env('MPESA_CONSUMER_KEY', ''),
            'consumer_secret'  => env('MPESA_CONSUMER_SECRET', ''),
            'shortcode'        => env('MPESA_SHORTCODE', ''),
            'passkey'          => env('MPESA_PASSKEY', ''),
        ],
        'mpesa_till' => [
            'enabled'          => env('MPESA_TILL_ENABLED', false),
            'label'            => 'M-Pesa Till',
            'environment'      => env('MPESA_TILL_ENV', 'sandbox'),
            'consumer_key'     => env('MPESA_TILL_CONSUMER_KEY', ''),
            'consumer_secret'  => env('MPESA_TILL_CONSUMER_SECRET', ''),
            'till_number'      => env('MPESA_TILL_NUMBER', ''),
            'passkey'          => env('MPESA_TILL_PASSKEY', ''),
        ],
        'kopokopo' => [
            'enabled'        => env('KOPOKOPO_ENABLED', false),
            'label'          => 'Kopokopo Till',
            'api_key'        => env('KOPOKOPO_API_KEY', ''),
            'client_id'      => env('KOPOKOPO_CLIENT_ID', ''),
            'client_secret'  => env('KOPOKOPO_CLIENT_SECRET', ''),
            'till_number'    => env('KOPOKOPO_TILL_NUMBER', ''),
            'webhook_url'    => env('KOPOKOPO_WEBHOOK_URL', ''),
            'environment'    => env('KOPOKOPO_ENV', 'sandbox'),
        ],
        'equity' => [
            'enabled'       => env('EQUITY_ENABLED', false),
            'label'         => 'Equity Bank',
            'api_key'       => env('EQUITY_API_KEY', ''),
            'api_secret'    => env('EQUITY_API_SECRET', ''),
            'merchant_code' => env('EQUITY_MERCHANT_CODE', ''),
            'account_no'    => env('EQUITY_ACCOUNT_NUMBER', ''),
            'callback_url'  => env('EQUITY_CALLBACK_URL', ''),
        ],
        'kcb' => [
            'enabled'      => env('KCB_ENABLED', false),
            'label'        => 'KCB Bank',
            'api_key'      => env('KCB_API_KEY', ''),
            'api_secret'   => env('KCB_API_SECRET', ''),
            'merchant_id'  => env('KCB_MERCHANT_ID', ''),
            'account_no'   => env('KCB_ACCOUNT_NUMBER', ''),
            'callback_url' => env('KCB_CALLBACK_URL', ''),
        ],
        'coop' => [
            'enabled'      => env('COOP_ENABLED', false),
            'label'        => 'Cooperative Bank',
            'api_key'      => env('COOP_API_KEY', ''),
            'api_secret'   => env('COOP_API_SECRET', ''),
            'account_no'   => env('COOP_ACCOUNT_NUMBER', ''),
            'callback_url' => env('COOP_CALLBACK_URL', ''),
        ],
    ],
];
